version: "3.4"

services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: build
    depends_on: [mongo]
    ports:
      - 8000:80
      - 6060:6060
    volumes:
      - ./server:/app
    command: watcher
    environment:
      ENV: local
      LOG_LEVEL: DEBUG
      MONGO_CONNECTION_URL: mongodb://mongo:27017
      PPROF: 1
      ADMIN_KEY: local

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017