version: "3.4"

services:

  server:
    build:
      context: server
      target: build
    depends_on: [mongo]
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    command: watcher

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017