version: "3.4"

services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: build
    depends_on: [mongo]
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    command: watcher
    environment:
      LOG_LEVEL: DEBUG

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017